version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    environment:
      - DB=redis
    restart: unless-stopped

  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mongo:
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  redis_data:
  mongo_data:
